### PR TITLE
Fixed configuration using forge configuration file handling

### PR DESCRIPTION
**Pull request by Keridos**
Debug level variable not done yet. Must be added later.
This is much cleaner than the original code. Why not use forge configuration file handling when it is offered?

### CODE REVIEW

**Comment by Keridos** [comment]
This also moves the config from ./wirelessredstone.properties to ./config/WirelessRedstoneCore.config. (The default for forge mods). People using different IDs might have to change the new file aswell.

**Comment by Keridos** [comment]
The Addons must be rewritten to use that handling aswell. I did not do that yet since I only looked at the main project. Maybe even refactor the entire source folders. Client and common can be merged since mods are universal for client and server now.

/edit: Btw, is there any way to get in touch with you directly, Eury? Would be nice to be able to chat with you about this mod outside of GitHub.

**Comment by Keridos** [comment]
It looks as if it had some more consequences in the power Config addon, when i try to use it in SP it crashes my game. Eury, could you take a look into that? Not sure though if the config thing did that. Did not test that before I changed the source.

**Comment by Eurymachus** [comment]
Hi Keridos, looks good.

Can you squash your commits into a single commit/Create a new pull request please.

So It's easier to read through the changes and then cleaner to merge.

Thanks.

**Pull request closed without merging**
